// This file was auto-generated by the vendorize.go script.
//
// This file is released under the MIT license but every source file it includes
// (directly and transitively) is in the public domain.
//
// Generated when the upstream repository was at commit REMOVEME.

#ifndef GOXZ_SKIP_C_COMPILATION
#include "src/liblzma/check/crc32_fast.c"
#endif
