// This file was auto-generated by the vendorize.go script.
//
// This file is released under the MIT license but every source file it includes
// (directly and transitively) is in the public domain.
//
// Generated when the upstream repository was at commit 2327a461e1afce862c22269b80d3517801103c1b.

#ifndef GOXZ_SKIP_C_COMPILATION
#include "upstream/src/liblzma/common/easy_preset.c"
#endif
