// This file was auto-generated by the vendorize.go script.
//
// This file is released under the MIT license but every source file it includes
// (directly and transitively) is in the public domain.
//
// Generated when the upstream repository was at commit e7da44d5151e21f153925781ad29334ae0786101.

#ifndef GOXZ_SKIP_C_COMPILATION
#include "upstream/src/liblzma/common/block_buffer_encoder.c"
#endif
