package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const cTemplate = `// This file was auto-generated by the vendorize.go script.
//
// This file is released under the MIT license but every source file it includes
// (directly and transitively) is in the public domain.
//
// Generated when the upstream repository was at commit %s.

#ifndef GOXZ_SKIP_C_COMPILATION
#include "%s"
#endif
`

const requiredUpstreamFiles = `
src/liblzma/api/lzma/base.h
src/liblzma/api/lzma/bcj.h
src/liblzma/api/lzma/block.h
src/liblzma/api/lzma/check.h
src/liblzma/api/lzma/container.h
src/liblzma/api/lzma/delta.h
src/liblzma/api/lzma/filter.h
src/liblzma/api/lzma/hardware.h
src/liblzma/api/lzma/index.h
src/liblzma/api/lzma/index_hash.h
src/liblzma/api/lzma/lzma12.h
src/liblzma/api/lzma/stream_flags.h
src/liblzma/api/lzma/version.h
src/liblzma/api/lzma/vli.h
src/liblzma/api/lzma.h

src/liblzma/check/check.c
src/liblzma/check/check.h
src/liblzma/check/crc32_fast.c
src/liblzma/check/crc32_table.c
src/liblzma/check/crc32_table_le.h
src/liblzma/check/crc64_fast.c
src/liblzma/check/crc64_table.c
src/liblzma/check/crc64_table_le.h
src/liblzma/check/crc_macros.h

src/liblzma/common/block_decoder.c
src/liblzma/common/block_decoder.h
src/liblzma/common/block_encoder.c
src/liblzma/common/block_encoder.h
src/liblzma/common/block_header_decoder.c
src/liblzma/common/block_header_encoder.c
src/liblzma/common/block_util.c
src/liblzma/common/common.c
src/liblzma/common/common.h
src/liblzma/common/easy_encoder.c
src/liblzma/common/easy_preset.c
src/liblzma/common/easy_preset.h
src/liblzma/common/filter_common.c
src/liblzma/common/filter_common.h
src/liblzma/common/filter_decoder.c
src/liblzma/common/filter_decoder.h
src/liblzma/common/filter_encoder.c
src/liblzma/common/filter_encoder.h
src/liblzma/common/filter_flags_decoder.c
src/liblzma/common/filter_flags_encoder.c
src/liblzma/common/index.c
src/liblzma/common/index.h
src/liblzma/common/index_encoder.c
src/liblzma/common/index_encoder.h
src/liblzma/common/index_hash.c
src/liblzma/common/memcmplen.h
src/liblzma/common/stream_decoder.c
src/liblzma/common/stream_decoder.h
src/liblzma/common/stream_encoder.c
src/liblzma/common/stream_flags_common.c
src/liblzma/common/stream_flags_common.h
src/liblzma/common/stream_flags_decoder.c
src/liblzma/common/stream_flags_encoder.c
src/liblzma/common/vli_decoder.c
src/liblzma/common/vli_encoder.c
src/liblzma/common/vli_size.c

src/liblzma/delta/delta_common.h
src/liblzma/delta/delta_decoder.h
src/liblzma/delta/delta_encoder.h

src/liblzma/lz/lz_decoder.c
src/liblzma/lz/lz_decoder.h
src/liblzma/lz/lz_encoder.c
src/liblzma/lz/lz_encoder.h
src/liblzma/lz/lz_encoder_hash.h
src/liblzma/lz/lz_encoder_mf.c

src/liblzma/lzma/fastpos.h
src/liblzma/lzma/fastpos_table.c
src/liblzma/lzma/lzma2_decoder.c
src/liblzma/lzma/lzma2_decoder.h
src/liblzma/lzma/lzma2_encoder.c
src/liblzma/lzma/lzma2_encoder.h
src/liblzma/lzma/lzma_common.h
src/liblzma/lzma/lzma_decoder.c
src/liblzma/lzma/lzma_decoder.h
src/liblzma/lzma/lzma_encoder.c
src/liblzma/lzma/lzma_encoder.h
src/liblzma/lzma/lzma_encoder_optimum_fast.c
src/liblzma/lzma/lzma_encoder_optimum_normal.c
src/liblzma/lzma/lzma_encoder_presets.c
src/liblzma/lzma/lzma_encoder_private.h

src/liblzma/rangecoder/price.h
src/liblzma/rangecoder/price_table.c
src/liblzma/rangecoder/range_common.h
src/liblzma/rangecoder/range_decoder.h
src/liblzma/rangecoder/range_encoder.h

src/liblzma/simple/simple_coder.h
src/liblzma/simple/simple_decoder.h
src/liblzma/simple/simple_encoder.h

src/common/mythread.h
src/common/sysdefs.h
src/common/tuklib_common.h
src/common/tuklib_config.h
src/common/tuklib_integer.h
`

const usage = `This script vendorizes C files in the upstream xz repository to this repo.
It MUST be run with the repo root as the current working directory.
Usage:

	go run internal/vendorize/vendorize.go [options]

Options:

`

var vendorizeAllFiles bool
var skipBuldAndTests bool
var optimizeFiles bool

func init() {
	flag.BoolVar(&vendorizeAllFiles, "all", false,
		"vendorize all files in the upstream repo, not just those explicitly required")
	flag.BoolVar(&skipBuldAndTests, "skip-build", false,
		"skip build and tests after vendorizing")
	flag.BoolVar(&optimizeFiles, "optimize", false,
		"optimize the files by removing source files not needed for the tests to pass")
}

func main() {
	flag.Usage = func() {
		_, _ = fmt.Fprintf(flag.CommandLine.Output(), usage)
		flag.PrintDefaults()
	}
	flag.Parse()

	_, err := upstreamGitHash()
	if err != nil {
		fmt.Println("Failed to determine the Git hash of the upstream repo:", err)
		os.Exit(1)
	}

	var files []string
	if vendorizeAllFiles {
		files, err = listAllCFilesInUpstream()
		if err != nil {
			fmt.Println("Failed to list all C files in upstream:", err)
			os.Exit(1)
		}
	} else {
		files = split(requiredUpstreamFiles)
	}

	if optimizeFiles {
		files = optimize(files)
	}

	if !vendorize(files, true) {
		os.Exit(1)
	}

	if optimizeFiles {
		fmt.Println("---REQUIRED FILE LIST FOLLOWS---")
		for _, file := range files {
			fmt.Println(file)
		}
	}
}

func optimize(files []string) []string {
	fmt.Println("Optimizing files")
	var required []string
	for i, file := range files {
		fmt.Printf("%d/%d\n", i+1, len(files))
		thisFiles := make([]string, i)
		copy(thisFiles, files[:i])
		thisFiles = append(thisFiles, files[i+1:]...)
		fmt.Printf("Testing the build without %s\n", file)
		if vendorize(thisFiles, false) {
			fmt.Println("!!Passed!!")
		} else {
			fmt.Println("  Failed")
			required = append(required, file)
		}
	}
	fmt.Printf("Required files: %d/%d\n", len(required), len(files))
	if len(required) < len(files) {
		fmt.Println("Performing another optimize round")
		return optimize(required)
	}
	return required
}

func vendorize(files []string, verbose bool) bool {
	removeVendorizedCFiles()
	gitHash := "REMOVEME"
	for _, file := range files {
		if verbose {
			fmt.Println("Vendorizing", file)
		}
		if err := vendorizeCFile(file, gitHash); err != nil {
			fmt.Printf("Failed to vendorize C file %s: %s", file, err)
			os.Exit(1)
		}
	}
	if skipBuldAndTests {
		return true
	}
	if verbose {
		fmt.Println("Running build and tests")
	}
	if !runBuildAndTests() {
		if verbose {
			fmt.Println("Build and tests failed! Run `go build -a goxz/goxz.go` to `go test ./...` to investigate.")
		}
		return false
	}
	if verbose {
		fmt.Println("Success")
	}
	return true
}

func listAllCFilesInUpstream() ([]string, error) {
	var files []string
	roots := []string{"internal/vendorize/upstream/src/liblzma", "internal/vendorize/upstream/src/common"}
	for _, root := range roots {
		err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
			if d.IsDir() {
				return nil
			}
			name := d.Name()
			if !strings.HasSuffix(name, ".c") && !strings.HasSuffix(name, ".h") {
				return nil
			}
			// The *tablegen.c files are helper files with main functions. Including them means the library can't
			// compile
			if strings.HasSuffix(name, "tablegen.c") {
				return nil
			}
			// The next two files are only for compilers without the standard bool C library. We don't support these.
			if name == "crc32_small.c" {
				return nil
			}
			if name == "crc64_small.c" {
				return nil
			}
			if name == "stream_encoder_mt.c" {
				return nil
			}
			relPath := strings.TrimPrefix(path, "internal/vendorize/upstream/")
			files = append(files, relPath)
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return files, nil
}

func runBuildAndTests() bool {
	return exec.Command("go", "build", "-a", "internal/goxz/goxz.go").Run() == nil &&
		exec.Command("go", "test", "./...").Run() == nil
}

func vendorizeCFile(upstreamFile string, gitHash string) error {
	b, err := os.ReadFile(filepath.Join("internal", "vendorize", "upstream", upstreamFile))
	if err != nil {
		return err
	}
	// TODO: validate that the file is in the public domain
	//  This doesn't cover header files but is probably good enough.
	//  Maybe we can transitively find header files that are included and audit them all
	vendorizedFile := filepath.Join("lzma", upstreamFile)
	if err := os.MkdirAll(filepath.Dir(vendorizedFile), 0777); err != nil {
		return err
	}
	if err := os.WriteFile(vendorizedFile, b, 0666); err != nil {
		return err
	}
	if !strings.HasSuffix(upstreamFile, ".c") {
		return nil
	}
	shimFile := "shim__" + strings.ReplaceAll(upstreamFile, "/", "__")
	content := fmt.Sprintf(cTemplate, gitHash, upstreamFile)
	return os.WriteFile(filepath.Join("lzma", shimFile), []byte(content), 0666)
}

func removeVendorizedCFiles() {
	_ = os.RemoveAll("lzma/src")
	entries, _ := os.ReadDir("lzma")
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "shim__src__") && strings.HasSuffix(entry.Name(), ".c") {
			_ = os.Remove(filepath.Join("lzma", entry.Name()))
		}
	}
}

// TODO: remove this and the git hash.
//  The git submodule is good enough
// upstreamGitHash determines the current hash of the upstream repo
func upstreamGitHash() (string, error) {
	return "", nil
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = "lzma/upstream"
	var buffer bytes.Buffer
	cmd.Stdout = &buffer
	err := cmd.Run()
	return strings.TrimSpace(buffer.String()), err
}

// split splits the string on newlines, removes empty lines and lines with a // prefix, and returns the trimmed strings
func split(s string) []string {
	var r []string
	for _, l := range strings.Split(strings.TrimSpace(s), "\n") {
		l = strings.TrimSpace(l)
		if l == "" {
			continue
		}
		if strings.HasPrefix(l, "//") {
			continue
		}
		r = append(r, l)
	}
	return r
}
